# Generated by Django 3.2.4 on 2021-06-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='aadhar_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='mobile_no',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
