# Generated by Django 3.2.4 on 2021-06-15 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('aadhar_no', models.IntegerField(unique=True)),
                ('dept', models.CharField(max_length=100)),
                ('desgn', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField(unique=True)),
                ('salary', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='credentials',
            fields=[
                ('emp_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                   to='employee.details')),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
