# Generated by Django 3.2.4 on 2021-06-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
