# Generated by Django 3.2.4 on 2021-06-16 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='crop',
            fields=[
                ('crop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('crop_name', models.CharField(max_length=40)),
                ('organic', models.BooleanField(default=False)),
                ('quality', models.CharField(max_length=5)),
                ('price_Kg', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('allocated_space', models.FloatField()),
                ('used_space', models.FloatField()),
                ('available_space', models.FloatField()),
                ('pincode', models.IntegerField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.crop')),
            ],
        ),
    ]
