# Generated by Django 3.2.4 on 2021-06-16 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('employee', '0006_remove_credentials_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='vechile',
            fields=[
                ('vechile_no', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pincode', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.details')),
            ],
        ),
        migrations.CreateModel(
            name='detail',
            fields=[
                ('order_no', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('pickup_date', models.DateField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.storage')),
                ('vechile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vechile')),
            ],
        ),
    ]
