# Generated by Django 3.2.4 on 2021-06-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='drop_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='pickup_date',
            field=models.DateField(null=True),
        ),
    ]
