# Generated by Django 3.2.4 on 2021-06-16 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('customer', '0003_remove_credentials_status'),
        ('employee', '0006_remove_credentials_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='procurement',
            fields=[
                ('order_no', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('bill_date', models.DateField()),
                ('price', models.FloatField()),
                ('status', models.CharField(max_length=30)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.crop')),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.details')),
            ],
        ),
        migrations.CreateModel(
            name='sale',
            fields=[
                ('order_no', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('bill_date', models.DateField()),
                ('price', models.FloatField()),
                ('status', models.CharField(max_length=30)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.crop')),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.details')),
            ],
        ),
        migrations.CreateModel(
            name='inspect',
            fields=[
                ('order',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='sales.procurement')),
                ('passed', models.BooleanField(default=False)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.details')),
            ],
        ),
    ]
