# Generated by Django 3.2.4 on 2021-06-16 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sales', '0002_auto_20210616_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspect',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
